import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, NativeSelect, PageHeader, TitleInput } from "@/components/app/inputs";
import { addLoan, addLoanRepayment, liveLoans, loanPaid, loanRemaining, useData } from "@/lib/db";
import { fmtDate, fmtPKR, todayISO } from "@/lib/format";
export const Route = createFileRoute("/loans")({
  head: () => ({ meta: [{ title: "Personal Loans — Mussa Enterprises" }, { name: "description", content: "Separate personal loans given, taken and repaid." }, { property: "og:title", content: "Personal Loans — Mussa Enterprises" }, { property: "og:description", content: "Separate personal loans given, taken and repaid." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Loans,
});
function Loans() { const d = useData(); const loans = liveLoans(d); const [open, setOpen] = useState(false); const [repay, setRepay] = useState<string>(); const payable = loans.filter((l) => l.direction === "taken").reduce((s, l) => s + loanRemaining(l), 0); const receivable = loans.filter((l) => l.direction === "given").reduce((s, l) => s + loanRemaining(l), 0); return <div><PageHeader title="Personal Loans" subtitle="Kept separate from business cash and reports" actions={<Button onClick={() => setOpen(true)}><Plus /> New Loan</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border-2 bg-sale-soft p-4"><div className="text-xs text-muted-foreground">Total Receivable</div><div className="num mt-1 text-2xl font-semibold text-sale">{fmtPKR(receivable)}</div></div><div className="rounded-lg border-2 bg-paid-soft p-4"><div className="text-xs text-muted-foreground">Total Payable</div><div className="num mt-1 text-2xl font-semibold text-paid">{fmtPKR(payable)}</div></div></div><div className="space-y-3">{loans.map((loan) => <div key={loan.id} className="rounded-lg border-2 bg-card p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{loan.person}</div><div className="text-xs text-muted-foreground">{loan.direction === "given" ? "Loan Given" : "Loan Taken"} · {fmtDate(loan.date)} · {loan.contact || "No contact"}</div></div><Button size="sm" variant="outline" onClick={() => setRepay(loan.id)}>Add Repayment</Button></div><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><div className="text-xs text-muted-foreground">Original</div><div className="num">{fmtPKR(loan.amount)}</div></div><div><div className="text-xs text-muted-foreground">Repaid</div><div className="num">{fmtPKR(loanPaid(loan))}</div></div><div><div className="text-xs text-muted-foreground">Remaining</div><div className="num font-semibold">{fmtPKR(loanRemaining(loan))}</div></div></div>{loan.particulars && <p className="mt-3 text-sm text-muted-foreground">{loan.particulars}</p>}</div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>New Personal Loan</DialogTitle></DialogHeader><LoanForm onDone={() => setOpen(false)} /></DialogContent></Dialog><Dialog open={!!repay} onOpenChange={(value) => !value && setRepay(undefined)}><DialogContent><DialogHeader><DialogTitle>Add Repayment</DialogTitle></DialogHeader>{repay && <RepaymentForm id={repay} onDone={() => setRepay(undefined)} />}</DialogContent></Dialog></div>; }
function LoanForm({ onDone }: { onDone: () => void }) { const [direction, setDirection] = useState<"given" | "taken">("given"); const [person, setPerson] = useState(""); const [contact, setContact] = useState(""); const [date, setDate] = useState(todayISO()); const [amount, setAmount] = useState(""); const [particulars, setParticulars] = useState(""); return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); const value = Number(amount); if (!person.trim() || value <= 0) { toast.error("Person and valid amount are required"); return; } addLoan({ direction, person: person.trim(), contact, date, amount: value, particulars }); toast.success("Personal loan saved"); onDone(); }}><Field label="Loan Type"><NativeSelect value={direction} onChange={(e) => setDirection(e.target.value as "given" | "taken")}><option value="given">Loan Given — Receivable</option><option value="taken">Loan Taken — Payable</option></NativeSelect></Field><Field label="Person *"><TitleInput value={person} onValueChange={setPerson} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Contact (optional)"><Input value={contact} onChange={(e) => setContact(e.target.value)} /></Field><Field label="Date"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field></div><Field label="Amount (Rs) *"><Input className="num" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9.]/g, ""))} /></Field><Field label="Particulars"><TitleInput value={particulars} onValueChange={setParticulars} /></Field><Button className="w-full">Save Loan</Button></form>; }
function RepaymentForm({ id, onDone }: { id: string; onDone: () => void }) { const [date, setDate] = useState(todayISO()); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); const value = Number(amount); if (value <= 0) { toast.error("Enter a valid amount"); return; } addLoanRepayment(id, { date, amount: value, note }); toast.success("Repayment added"); onDone(); }}><Field label="Date"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Amount (Rs)"><Input className="num" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9.]/g, ""))} /></Field><Field label="Note"><TitleInput value={note} onValueChange={setNote} /></Field><Button className="w-full">Save Repayment</Button></form>; }