/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as LedgerIdRouteImport } from './routes/ledger.$id'
import { Route as VoucherIdRouteImport } from './routes/voucher.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIdRoute = LedgerIdRouteImport.update({
  id: '/ledger/$id',
  path: '/ledger/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherIdRoute = VoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/entries': typeof EntriesRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/voucher/$id': typeof VoucherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/entries': typeof EntriesRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/voucher/$id': typeof VoucherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/entries': typeof EntriesRoute
  '/ledger/$id': typeof LedgerIdRoute
  '/voucher/$id': typeof VoucherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts' | '/entries' | '/ledger/$id' | '/voucher/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts' | '/entries' | '/ledger/$id' | '/voucher/$id'
  id:
    '__root__' | '/' | '/accounts' | '/entries' | '/ledger/$id' | '/voucher/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  EntriesRoute: typeof EntriesRoute
  LedgerIdRoute: typeof LedgerIdRoute
  VoucherIdRoute: typeof VoucherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$id': {
      id: '/ledger/$id'
      path: '/ledger/$id'
      fullPath: '/ledger/$id'
      preLoaderRoute: typeof LedgerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/$id': {
      id: '/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/voucher/$id'
      preLoaderRoute: typeof VoucherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  EntriesRoute: EntriesRoute,
  LedgerIdRoute: LedgerIdRoute,
  VoucherIdRoute: VoucherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
